version: '3.1'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./src:/src
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - php-network
    php:
        image: php:fpm
        volumes:
            - ./src:/src
        networks:
            - php-network

networks:
    php-network:
        driver: bridge